# -*- coding: utf-8 -*-
"""PD2 Sanctuary of Exile 中文翻译词典 — 武器/护甲基础物品名。
参考暗黑破坏神 2 中文社区标准译名（impk / 凯恩之角 / D2 官方中文版）。
完整名称精确映射，不做子串替换，避免误伤。
"""

WEAPON_NAMES = {
    "2H Phase Blade": "双手幻化之刃",
    "Ancient Axe": "古代之斧",
    "Ancient Sword": "古代之剑",
    "Arbalest": "劲弩",
    "Archon Staff": "执政官之杖",
    "Ashwood Bow": "梣木弓",
    "Ataghan": "弯月刀",
    "Axe": "斧",
    "Balanced Axe": "平衡斧",
    "Balanced Knife": "平衡小刀",
    "Balista": "重弩",
    "Ballista": "攻城弩",
    "Balrog Blade": "炎魔之刃",
    "Balrog Spear": "炎魔之矛",
    "Barbed Club": "倒刺棍棒",
    "Bardiche": "阔头枪",
    "Bastard Sword": "混种大剑",
    "Battle Axe": "战斗斧",
    "Battle Cestus": "战斗拳刃",
    "Battle Dart": "战斗飞镖",
    "Battle Hammer": "战斗锤",
    "Battle Scythe": "战斗镰刀",
    "Battle Staff": "战斗法杖",
    "Battle Sword": "战斗剑",
    "Bearded Axe": "长柄斧",
    "Bec-de-Corbin": "鸦嘴战锤",
    "Berserker Axe": "狂战士之斧",
    "Bill": "钩镰枪",
    "Blade": "刀刃",
    "Blade Bow": "刀锋弓",
    "Blade Talons": "刃爪",
    "Bone Knife": "骨小刀",
    "Bone Wand": "骨杖",
    "Brandistock": "三叉枪",
    "Broad Axe": "阔斧",
    "Broad Sword": "阔剑",
    "Burnt Wand": "烧焦之杖",
    "Caduceus": "神使之杖",
    "Cedar Bow": "雪松弓",
    "Cedar Staff": "雪松法杖",
    "Ceremonial Bow": "典礼长弓",
    "Ceremonial Javelin": "典礼标枪",
    "Ceremonial Pike": "典礼长枪",
    "Ceremonial Spear": "典礼长矛",
    "Cestus": "拳刃",
    "Champion Axe": "冠军之斧",
    "Champion Sword": "冠军之剑",
    "Chu-Ko-Nu": "诸葛弩",
    "Cinquedeas": "五刃剑",
    "Clasped Orb": "握扣之球",
    "Claws": "爪",
    "Claymore": "双刃大刀",
    "Cleaver": "砍刀",
    "Cloudy Sphere": "云雾之球",
    "Club": "棍棒",
    "Colossal Sword": "巨神之剑",
    "Colossus Blade": "巨神之刃",
    "Colossus Crossbow": "巨神十字弓",
    "Colossus Sword": "巨神长剑",
    "Colossus Voulge": "巨神戟",
    "Composite Bow": "组合弓",
    "Conquest Sword": "征服之剑",
    "Crossbow": "十字弓",
    "Crowbill": "鸦嘴锄",
    "Crumbling Maul": "碎骨之锤",
    "Crusader Bow": "十字军之弓",
    "Cryptic Axe": "秘仪之斧",
    "Cryptic Sword": "秘仪之剑",
    "Crystal Sword": "水晶剑",
    "Crystalline Globe": "水晶之球",
    "Cudgel": "短棍",
    "Cutlass": "弯刀",
    "Dacian Falx": "达契亚镰刀",
    "Dagger": "匕首",
    "Decapitator": "刽子手之斧",
    "Demon Crossbow": "恶魔十字弓",
    "Demon Heart": "恶魔之心",
    "Devil Star": "恶魔流星锤",
    "Diamond Bow": "钻石弓",
    "Dimensional Blade": "次元之刃",
    "Dimensional Shard": "次元碎片",
    "Dirk": "短剑",
    "Disintegrating Maul": "碎裂之锤",
    "Divine Scepter": "神圣权杖",
    "Double Axe": "双刃斧",
    "Double Bow": "双弓",
    "Dragon Stone": "龙之石",
    "Eagle Orb": "鹰之宝珠",
    "Edge Bow": "锋锐弓",
    "Elder Staff": "长老之杖",
    "Eldritch Orb": "怪异之球",
    "Elegant Blade": "优雅之刃",
    "Espadon": "宽刃剑",
    "Espandon": "宽刃剑",
    "Ettin Axe": "双头斧",
    "Executioner Sword": "行刑之剑",
    "Falcata": "弯刃刀",
    "Falchion": "弯月刀",
    "Fanged Knife": "牙刃",
    "Fascia": "束带刃",
    "Feral Axe": "野性之斧",
    "Feral Claws": "野性之爪",
    "Flail": "连枷",
    "Flamberge": "焰形剑",
    "Flanged Mace": "凸缘钉头锤",
    "Flying Axe": "飞行斧",
    "Flying Knife": "飞行小刀",
    "Francisca": "法兰克飞斧",
    "Fuscina": "鱼叉",
    "Ghost Glaive": "幽魂战戟",
    "Ghost Spear": "幽魂之矛",
    "Ghost Wand": "幽魂之杖",
    "Giant Axe": "巨战斧",
    "Giant Sword": "巨剑",
    "Giant Thresher": "巨型镰刀",
    "Gladius": "罗马短剑",
    "Glaive": "战戟",
    "Glorious Axe": "荣耀之斧",
    "Glowing Orb": "发光之球",
    "Gnarled Staff": "节瘤法杖",
    "Gorgon Crossbow": "蛇魔十字弓",
    "Gothic Axe": "哥特之斧",
    "Gothic Bow": "哥特之弓",
    "Gothic Staff": "哥特法杖",
    "Gothic Sword": "哥特之剑",
    "Grand Matron Bow": "大院长之弓",
    "Grand Scepter": "大权杖",
    "Grave Wand": "墓地之杖",
    "Great Axe": "大斧",
    "Great Bow": "大弓",
    "Great Maul": "大锤",
    "Great Pilum": "大投枪",
    "Great Poleaxe": "大战戟",
    "Great Sword": "大剑",
    "Greater Claws": "巨爪",
    "Greater Talons": "巨鹰爪",
    "Grim Scythe": "残酷镰刀",
    "Grim Wand": "残酷之杖",
    "Halberd": "长柄战斧",
    "Hand Axe": "手斧",
    "Hand Scythe": "手镰",
    "Harpoon": "鱼叉",
    "Hatchet": "短柄斧",
    "Hatchet Hands": "手斧拳套",
    "Heavenly Stone": "天堂之石",
    "Heavy Crossbow": "重十字弓",
    "Highland Blade": "高地之剑",
    "Holy Water Sprinkler": "圣水之杖",
    "Horadric Staff": "赫拉迪克法杖",
    "Hunter's Bow": "猎弓",
    "Hurlbat": "投掷斧",
    "Hydra Bow": "九头蛇弓",
    "Hydra Edge": "九头蛇之刃",
    "Hyperion Javelin": "亥伯龙标枪",
    "Hyperion Spear": "亥伯龙之矛",
    "Jagged Star": "锯齿流星锤",
    "Jared's Stone": "贾瑞德之石",
    "Javelin": "标枪",
    "Jo Staff": "僧院法杖",
    "Katar": "拳剑",
    "Khalim's Flail": "克林姆的连枷",
    "Khalim's Will": "克林姆的意志",
    "KhalimFlail": "克林姆连枷",
    "Knout": "皮鞭",
    "Kris": "马来匕首",
    "Kriss": "马来匕首",
    "Lance": "长枪",
    "Large Axe": "巨斧",
    "Large Siege Bow": "大攻城弓",
    "Legend Spike": "传说尖刺",
    "Legend Sword": "传说之剑",
    "Legendary Mallet": "传说之锤",
    "Lich Wand": "巫妖之杖",
    "Light Crossbow": "轻十字弓",
    "Lochaber Axe": "洛查伯战斧",
    "Long Battle Bow": "长战斗弓",
    "Long Bow": "长弓",
    "Long Siege Bow": "长攻城弓",
    "Long Staff": "长法杖",
    "Long Sword": "长剑",
    "Long War Bow": "长战弓",
    "Mace": "钉头锤",
    "Maiden Javelin": "少女标枪",
    "Maiden Pike": "少女长枪",
    "Maiden Spear": "少女长矛",
    "Mancatcher": "捕人叉",
    "Martel de Fer": "铁锤",
    "Matriarchal Bow": "女族长之弓",
    "Matriarchal Javelin": "女族长标枪",
    "Matriarchal Pike": "女族长长枪",
    "Matriarchal Spear": "女族长之矛",
    "MatriarchalJavelin": "女族长标枪",
    "Maul": "巨锤",
    "Mighty Scepter": "威猛权杖",
    "Military Axe": "军用斧",
    "Military Pick": "军用锹",
    "Mithral Point": "秘银尖枪",
    "Mithril Point": "秘银尖枪",
    "Morning Star": "晨星锤",
    "Mythical Sword": "神话之剑",
    "Naga": "蛇刀",
    "Ogre Axe": "食人魔之斧",
    "Ogre Maul": "食人魔之锤",
    "Partizan": "阔头枪",
    "Pellet Bow": "弹丸弓",
    "Petrified Wand": "石化之杖",
    "Phase Blade": "幻化之刃",
    "Pike": "长枪",
    "Pilum": "投枪",
    "Poignard": "刺剑",
    "Poleaxe": "长柄斧",
    "Polished Wand": "抛光之杖",
    "Quarterstaff": "长柄法杖",
    "Quhab": "曲刃拳剑",
    "Razor Bow": "剃刀之弓",
    "Reflex Bow": "反射弓",
    "Reinforced Mace": "强化钉头锤",
    "Repeating Crossbow": "连射十字弓",
    "Rondel": "圆刃匕首",
    "Ruination Maul": "毁灭之锤",
    "Rune Bow": "符文之弓",
    "Rune Scepter": "符文权杖",
    "Rune Staff": "符文法杖",
    "Rune Sword": "符文之剑",
    "Runic Talons": "符文之爪",
    "Saber": "军刀",
    "Sabre": "军刀",
    "Sacred Globe": "神圣之球",
    "Scepter": "权杖",
    "Scimitar": "弯刀",
    "Scissors Katar": "剪刃拳剑",
    "Scissors Quhab": "剪刃拳刀",
    "Scissors Suwayyah": "剪刃苏瓦雅",
    "Scourge": "天罚之锤",
    "Scythe": "镰刀",
    "Seraph Rod": "炽天使之杖",
    "Shadow Bow": "暗影弓",
    "Shamshir": "波斯弯刀",
    "Shillelagh": "橡木短棍",
    "Shillelah": "橡木短棍",
    "Short Battle Bow": "短战斗弓",
    "Short Bow": "短弓",
    "Short Siege Bow": "短攻城弓",
    "Short Spear": "短矛",
    "Short Staff": "短法杖",
    "Short Sword": "短剑",
    "Short War Bow": "短战弓",
    "Siege Crossbow": "攻城十字弓",
    "Silver Edged Axe": "银刃斧",
    "Silver-edged Axe": "银刃斧",
    "Simbilan": "辛比兰战矛",
    "Small Crescent": "小弯刀",
    "Smoked Sphere": "烟熏之球",
    "Sparkling Ball": "闪耀之球",
    "Spear": "长矛",
    "Spetum": "梭镖枪",
    "Spiculum": "投矛",
    "Spider Bow": "蜘蛛弓",
    "Spiked Club": "钉锤",
    "Stag Bow": "牡鹿之弓",
    "Stalagmite": "石笋之锤",
    "Stilleto": "狭长匕首",
    "Stygian Pike": "冥河长枪",
    "Stygian Pilum": "冥河投枪",
    "SuperKhalimFlail": "超级克林姆连枷",
    "Suwayyah": "苏瓦雅",
    "Swirling Crystal": "漩涡之球",
    "Tabar": "塔巴尔战斧",
    "Thresher": "镰刀",
    "Throwing Axe": "投掷斧",
    "Throwing Knife": "投掷小刀",
    "Throwing Spear": "投掷长矛",
    "Thunder Maul": "雷锤",
    "Tomahawk": "战斧",
    "Tomb Wand": "坟墓之杖",
    "Trident": "三叉戟",
    "Truncheon": "警棍",
    "Tulwar": "塔瓦弯刀",
    "Tusk Sword": "獠牙剑",
    "Twin Axe": "双斧",
    "Two-Hand Phase Blade": "双手幻化之刃",
    "Two-Handed Sword": "双手剑",
    "Tyrant Club": "暴君之棍",
    "Unearthed Wand": "出土之杖",
    "Vortex Orb": "漩涡之球",
    "Voulge": "战戟",
    "Walking Stick": "步行杖",
    "Wand": "法杖",
    "War Axe": "战斧",
    "War Club": "战棍",
    "War Dart": "战镖",
    "War Fist": "战拳",
    "War Fork": "战叉",
    "War Hammer": "战锤",
    "War Javelin": "战枪",
    "War Pike": "战枪",
    "War Scepter": "战权杖",
    "War Scythe": "战镰",
    "War Spear": "战矛",
    "War Spike": "战刺",
    "War Staff": "战法杖",
    "War Sword": "战剑",
    "Ward Bow": "守护之弓",
    "Winged Axe": "翼斧",
    "Winged Harpoon": "翼鱼叉",
    "Winged Knife": "翼刀",
    "Wrist Blade": "腕刃",
    "Wrist Spike": "腕刺",
    "Wrist Sword": "腕剑",
    "Yari": "日式长枪",
    "Yew Wand": "紫杉之杖",
    "Zweihander": "双手巨剑",
}

ARMOR_NAMES = {
    "Aegis": "圣盾",
    "Aerin Shield": "艾琳之盾",
    "Akaran Rondache": "艾卡拉圆盾",
    "Akaran Targe": "艾卡拉小盾",
    "Alpha Helm": "阿尔法头盔",
    "Ancient Armor": "古代装甲",
    "Ancient Shield": "古代之盾",
    "Antlers": "鹿角",
    "Archon Plate": "执政官铠甲",
    "Armet": "轻盔",
    "Assault Helmet": "突击头盔",
    "Avenger Guard": "复仇者头盔",
    "Balrog Skin": "炎魔皮板甲",
    "Barbed Shield": "倒刺盾",
    "Baroque Round Shield": "巴洛克圆盾",
    "Basinet": "轻钢盔",
    "Battle Belt": "战斗腰带",
    "Battle Boots": "战斗靴",
    "Battle Gauntlets": "战斗手套",
    "Belt(M)": "腰带(M)",
    "Blade Barrier": "刀锋盾",
    "Blessed Helmet": "祝福头盔",
    "Blood Spirit": "血之灵",
    "Blood Spirt": "血之灵",
    "Bloodlord Skull": "血王之首",
    "Bone Helm": "骸骨头盔",
    "Bone Shield": "白骨之盾",
    "Bone Visage": "骸骨面甲",
    "Boneweave": "骨织甲",
    "Boneweave Boots": "骨织靴",
    "Boneweave [S]": "骨织甲[S]",
    "Bracers(M)": "护腕(M)",
    "Bramble Mitts": "荆棘手套",
    "Breast Plate": "胸甲",
    "Buckler": "小圆盾",
    "Cantor Trophy": "唱诗者之首",
    "Cap": "帽子",
    "Cap/hat": "帽子",
    "Carnage Helm": "屠杀头盔",
    "Casque": "轻便头盔",
    "Chain Boots": "锁链靴",
    "Chain Gloves": "锁链手套",
    "Chain Mail": "锁子甲",
    "Chaos Armor": "混沌铠甲",
    "Circlet": "头环",
    "Colossus Girdle": "巨神腰带",
    "Combat Belt": "战斗腰带",
    "Conquerer Crown": "征服者王冠",
    "Conqueror Crown": "征服者王冠",
    "Corona": "王冠",
    "Coronet": "宝冠",
    "Crown": "皇冠",
    "Crown Shield": "皇冠之盾",
    "Crusader Gauntlets": "十字军手套",
    "Cuirass": "胸甲",
    "Death Mask": "死亡面具",
    "Defender": "防御者盾",
    "Demon Head": "恶魔之首",
    "Demonhead": "恶魔头盖骨",
    "Demonhide Armor": "魔皮战甲",
    "Demonhide Boots": "魔皮靴",
    "Demonhide Gloves": "魔皮手套",
    "Demonhide Sash": "魔皮腰带",
    "Destroyer Helm": "毁灭者头盔",
    "Diadem": "头冠",
    "Diamond Mail": "钻石锁子甲",
    "Dragon Shield": "龙盾",
    "Dream Spirit": "梦之灵",
    "Dusk Shroud": "灰暮寿衣",
    "Earth Spirit": "大地之灵",
    "Elegant Round Shield": "优雅圆盾",
    "Embossed Plate": "浮雕板甲",
    "Enlightened Robe": "开明长袍",
    "Falcon Mask": "猎鹰面具",
    "Fanged Helm": "獠牙头盔",
    "Fetish Trophy": "图腾面具",
    "Field Belt": "战场腰带",
    "Field Plate": "战甲",
    "Full Helm": "高级头盔",
    "Full Plate Mail": "全身板甲",
    "Fury Visor": "狂怒面甲",
    "Gargoyle Head": "石魔像之首",
    "Gaunlets(H)": "手套(H)",
    "Gauntlets": "手套",
    "Ghost Armor": "鬼魂战甲",
    "Giant Conch": "巨螺",
    "Gilded Shield": "镀金盾",
    "Girdle(H)": "束带(H)",
    "Gloves(L)": "手套(L)",
    "Gothic Plate": "哥特板甲",
    "Gothic Shield": "哥特盾",
    "Grand Crown": "大皇冠",
    "Great Hauberk": "大锁子甲",
    "Great Helm": "巨盔",
    "Greaves": "胫甲",
    "Griffon Headdress": "狮鹫头饰",
    "Griffon Headress": "狮鹫头饰",
    "Grim Helm": "冷酷头盔",
    "Grim Shield": "冷酷之盾",
    "Guardian Crown": "守护者王冠",
    "Guilded Shield": "镀金盾",
    "Hard Leather Armor": "硬皮甲",
    "Hawk Helm": "鹰头盔",
    "Heater": "火炉盾",
    "Heavy Belt": "重腰带",
    "Heavy Boots": "重靴",
    "Heavy Bracers": "重护腕",
    "Heavy Gloves": "重手套",
    "Heirophant Trophy": "圣职者之首",
    "Hellforge Plate": "地狱熔炉板甲",
    "Hellforged Plate": "地狱熔炉板甲",
    "Hellspawn Skull": "地狱之子之首",
    "Helm": "头盔",
    "Heraldic Shield": "纹章盾",
    "Hierophant Trophy": "圣职者之首",
    "Horned Helm": "角盔",
    "Hunter Hood": "猎人头罩",
    "Hunter's Guise": "猎人之面",
    "Hydraskull": "九头蛇之首",
    "Hyperion": "亥伯龙盾",
    "Jawbone Cap": "颚骨帽",
    "Jawbone Visor": "颚骨面甲",
    "Kite Shield": "鸢盾",
    "Kraken Shell": "北海巨妖之壳",
    "Kurast Shield": "库拉斯特盾",
    "Lacquered Plate": "漆甲",
    "Large Shield": "大盾",
    "Leather Armor": "皮甲",
    "Leather Boots": "皮靴",
    "Leather Gloves": "皮手套",
    "Leather Hood": "皮头罩",
    "Light Belt": "轻腰带",
    "Light Gauntlets": "轻手套",
    "Light Plate": "轻型装甲",
    "Light Plate Boots": "轻板靴",
    "Light Plated Boots": "轻板靴",
    "Linked Mail": "环甲",
    "Lion Helm": "狮头盔",
    "Loricated Mail": "鳞甲",
    "Luna": "月盾",
    "Mage Plate": "法师铠甲",
    "Mask": "面具",
    "Mesh Armor": "网眼甲",
    "Mesh Belt": "网眼腰带",
    "Mesh Boots": "网眼靴",
    "Minion Skull": "仆从之首",
    "Mirrored Boots": "镜面靴",
    "Mithril Coil": "秘银腰带",
    "Monarch": "统治者大盾",
    "Mummified Trophy": "木乃伊之首",
    "Myrmidon Greaves": "侍卫胫甲",
    "Mythic Belt": "神话腰带",
    "Ogre Gauntlets": "食人魔手套",
    "Ornate Armor": "华丽战甲",
    "Ornate Plate": "华丽板甲",
    "Overseer Skull": "监工之首",
    "Pavise": "大盾",
    "Pious Helmet": "虔诚头盔",
    "Plate Boots": "板甲靴",
    "Plate Mail": "板甲",
    "Plated Belt": "板条腰带",
    "Preserved Head": "保存之首",
    "Protector Shield": "保护者盾",
    "Quilted Armor": "棉布甲",
    "Rage Mask": "狂怒面具",
    "Ring Mail": "环状甲",
    "Rondache": "圆盾",
    "Round Shield": "圆盾",
    "Royal Shield": "皇家盾",
    "Russet Armor": "赤褐甲",
    "Rustic Belt": "乡村腰带",
    "Sacred Armor": "神圣铠甲",
    "Sacred Feathers": "神圣羽毛",
    "Sacred Rondache": "神圣圆盾",
    "Sacred Targe": "神圣小盾",
    "Sainted Helmet": "圣洁头盔",
    "Sallet": "轻型头盔",
    "Sash": "饰带",
    "Sash(L)": "饰带(L)",
    "Savage Helmet": "野蛮头盔",
    "Scale Mail": "鳞甲",
    "Scarab Husk": "圣甲虫壳甲",
    "Scarabshell Boots": "圣甲虫壳靴",
    "Scutum": "长盾",
    "Serpentskin Armor": "蛇皮甲",
    "Sexton Trophy": "司事之首",
    "Shabby Hood": "破旧头罩",
    "Shadow Plate": "阴影铠甲",
    "Shako": "谐角之冠",
    "Sharkskin Belt": "鲨皮腰带",
    "Sharkskin Boots": "鲨皮靴",
    "Sharkskin Gloves": "鲨皮手套",
    "Sharktooth Armor": "鲨齿甲",
    "Silk Robe": "丝绸长袍",
    "Simple Robe": "简朴长袍",
    "Skull Cap": "骷髅帽",
    "Sky Spirit": "天穹之灵",
    "Slayer Guard": "杀戮者头盔",
    "Small Shield": "小盾",
    "Socketed Boneweave": "带孔骨织甲",
    "Socketed Troll Belt": "带孔巨魔腰带",
    "Spiderweb Sash": "蛛网腰带",
    "Spiked Shield": "尖刺盾",
    "Spired Helm": "尖顶头盔",
    "Spirit Mask": "幽灵面具",
    "Splendid Round Shield": "华丽圆盾",
    "Splint Mail": "镶板甲",
    "Studded Leather": "镶嵌甲",
    "Succubae Skull": "魅魔之首",
    "Succubus Skull": "魅魔之首",
    "Sun Spirit": "太阳之灵",
    "Targe": "小盾",
    "Tattered Robe": "破旧长袍",
    "Templar Coat": "圣堂武士外套",
    "Tiara": "三重冠",
    "Tigulated Mail": "叠瓦甲",
    "Totemic Mask": "图腾面具",
    "Tower Shield": "塔盾",
    "Trellised Armor": "格栅甲",
    "Troll Belt": "巨魔腰带",
    "Troll Belt [S]": "巨魔腰带[S]",
    "Troll Nest": "巨魔巢穴",
    "Unraveller Head": "解缚者之首",
    "Utility Belt": "实用腰带",
    "Vambraces": "护腕",
    "Vampirebone Gloves": "吸血鬼骸骨手套",
    "Vampirefang Belt": "吸血鬼獠牙腰带",
    "Vanguard Belt": "先锋腰带",
    "Vortex Shield": "漩涡盾",
    "War Belt": "战腰带",
    "War Boots": "战靴",
    "War Gaunlets": "战手套",
    "War Gauntlets": "战手套",
    "War Hat": "战帽",
    "Ward": "守卫盾",
    "Winged Helm": "翼盔",
    "Winged helm": "翼盔",
    "Wire Fleece": "线羊毛皮甲",
    "Wolf Head": "狼头",
    "Wyrmhide": "虫壳甲",
    "Wyrmhide Boots": "虫壳靴",
    "Zakarum Shield": "萨卡兰姆盾",
    "Zombie Head": "僵尸之首",
    # 已翻译条目（保持幂等）
    "头盔": "头盔",
    "腰带": "腰带",
    "靴子": "靴子",
}
