# -*- coding: utf-8 -*-
"""PD2 Sanctuary of Exile 中文翻译词典 — 属性/词缀字符串专用。
短语按长度降序匹配，保证最长优先。"""

# (英文短语, 中文) — 按长度降序使用
PROP_PHRASES = [
    # --- 施法/光环类 (结构化, 优先于普通短语) ---
    ("Level ", "等级 "),  # 特殊: 由正则处理, 此处不启用

    # --- 复合短语 (长优先) ---
    ("Damage Taken Gained as Mana when Hit", "受击时承受伤害的百分比转化为法力"),
    ("Better Chance of Getting Magic Item", "更好的机会获得魔法装备"),
    ("Chance of Getting Magic Item", "机会获得魔法装备"),
    ("Increased Chance of Blocking", "增加格挡几率"),
    ("Chance to Uninterruptible Cast", "施法不被中断几率"),
    ("Damage Taken Gained as Mana", "承受伤害的百分比转化为法力"),
    ("Damage Taken Gained as Life", "承受伤害的百分比转化为生命"),
    ("Maximum Physical Resist", "物理抗性上限"),
    ("Maximum Fire Resist", "火焰抗性上限"),
    ("Maximum Cold Resist", "冰冷抗性上限"),
    ("Maximum Lightning Resist", "闪电抗性上限"),
    ("Maximum Poison Resist", "毒素抗性上限"),
    ("Enhanced Maximum Damage", "增强最大伤害"),
    ("Physical Damage Reduction", "物理伤害减少"),
    ("Magic Damage Reduction", "魔法伤害减少"),
    ("Physical Damage Taken", "受到的物理伤害"),
    ("Elemental Damage Taken", "受到的元素伤害"),
    ("Increased Maximum Life", "增加最大生命"),
    ("Increased Maximum Mana", "增加最大法力"),
    ("Faster Cast Rate", "施法速度"),
    ("Faster Hit Recovery", "快速打击恢复"),
    ("Faster Block Rate", "快速格挡率"),
    ("Faster Run/Walk", "跑步/行走速度"),
    ("Increased Attack Speed", "攻击速度"),
    ("Attack Speed", "攻击速度"),
    ("Deadly Strike", "致命攻击"),
    ("Crushing Blow", "压碎性打击"),
    ("Open Wounds", "撕裂伤口"),
    ("Ignores Target Defense", "忽略目标防御"),
    ("Target Defense", "目标防御"),
    ("Damage to Demons", "对恶魔的伤害"),
    ("Damage to Undead", "对不死生物的伤害"),
    ("Damage to Beasts", "对野兽的伤害"),
    ("Damage Reduced by", "伤害减少"),
    ("Damage Reduction", "伤害减少"),
    ("Enhanced Damage", "增强伤害"),
    ("Maximum Damage", "最大伤害"),
    ("Minimum Damage", "最小伤害"),
    ("Increased Maximum Damage", "增加最大伤害"),
    ("Physical Damage", "物理伤害"),
    ("Magic Damage", "魔法伤害"),
    ("Elemental Damage", "元素伤害"),
    ("Poison and Bone Skills", "毒素与白骨技能"),
    ("Poison and Bone Spells", "毒素与白骨法术"),
    ("Summoning Skills", "召唤系技能"),
    ("Offensive Auras", "攻击灵气"),
    ("Defensive Auras", "防御灵气"),
    ("Shadow Disciplines", "影子训练"),
    ("Passive and Magic Skills", "被动与魔法技能"),
    ("Passive Skills", "被动技能"),
    ("Elemental Skills", "元素技能"),
    ("Shape Shifting Skills", "变形系技能"),
    ("Combat Skills", "战斗技能"),
    ("Combat Masteries", "战斗精通"),
    ("Martial Arts", "武术"),
    ("Skill Levels", "技能等级"),
    ("All Skills", "所有技能"),
    ("Cold Skills", "冰冷系技能"),
    ("Fire Skills", "火焰系技能"),
    ("Lightning Skills", "闪电系技能"),
    ("Poison Skills", "毒素系技能"),
    ("Spell Projectile(s)", "法术投射物"),
    ("Attack Projectile(s)", "攻击投射物"),
    ("Attack Strikes", "攻击次数"),
    ("Attack Rating", "攻击准确率"),
    ("Light Radius", "光照范围"),
    ("Cannot Be Frozen", "无法冰冻"),
    ("Half Freeze Duration", "冰冻持续时间减半"),
    ("Cannot Be Repaired", "无法修复"),
    ("Replenish Quantity", "恢复数量"),
    ("Replenishes Quantity", "恢复数量"),
    ("Maximum Durability", "最大耐久度"),
    ("Reduced Requirements", "降低需求"),
    ("Requirements", "需求"),
    ("Piercing Attack", "穿刺攻击"),
    ("Piercing", "穿刺"),
    ("Hit Slows Target", "命中时减慢目标速度"),
    ("Slows Target", "减慢目标速度"),
    ("Freezes Target", "冰冻目标"),
    ("Hit Freezes Target", "命中时冰冻目标"),
    ("Hit Blinds Target", "命中时致盲目标"),
    ("Blinds Target", "致盲目标"),
    ("Hit Causes Monster to Flee", "命中时使怪物逃跑"),
    ("Causes Monster to Flee", "使怪物逃跑"),
    ("Monster to Flee", "怪物逃跑"),
    ("Knockback", "击退"),
    ("Hit Causes", "命中时使"),
    ("Freeze Length Reduced by", "冰冻持续时间减少"),
    ("Poison Length Reduced by", "毒素持续时间减少"),
    ("Curse Length Reduced by", "诅咒持续时间减少"),
    ("Duration Reduced by", "持续时间减少"),
    ("Reduced by", "减少"),
    ("All Resistances", "所有抗性"),
    ("Fire Resistance", "火焰抗性"),
    ("Cold Resistance", "冰冷抗性"),
    ("Lightning Resistance", "闪电抗性"),
    ("Poison Resistance", "毒素抗性"),
    ("Physical Resistance", "物理抗性"),
    ("Resist All", "全抗"),
    ("Resist Fire", "抗火"),
    ("Resist Cold", "抗寒"),
    ("Resist Lightning", "抗闪电"),
    ("Resist Poison", "抗毒"),
    ("Lower Resist", "降低抗性"),
    ("All Attributes", "所有属性"),
    ("Life after each Demon Kill", "每击杀一个恶魔后获得生命"),
    ("Mana after each Demon Kill", "每击杀一个恶魔后获得法力"),
    ("Life after each Kill", "每击杀一个敌人后获得生命"),
    ("Mana after each Kill", "每击杀一个敌人后获得法力"),
    ("Life stolen per hit", "每次命中偷取生命"),
    ("Mana stolen per hit", "每次命中偷取法力"),
    ("Life Stolen per Hit", "每次命中偷取生命"),
    ("Mana Stolen per Hit", "每次命中偷取法力"),
    ("Replenish Life", "生命回复"),
    ("Regenerate Mana", "法力回复"),
    ("Regenerate Stamina", "耐力回复"),
    ("Life after each", "每击杀后获得生命"),
    ("Mana after each", "每击杀后获得法力"),
    ("Extra Gold from Monsters", "从怪物身上额外获得金币"),
    ("Gold from Monsters", "从怪物身上获得金币"),
    ("Extra Gold", "额外金币"),
    ("Experience Gained", "获得的经验值"),
    ("Experience", "经验值"),
    ("Attack Rating against Undead", "对不死生物的攻击准确率"),
    ("Attack Rating against Demons", "对恶魔的攻击准确率"),
    ("Attack Rating against Beasts", "对野兽的攻击准确率"),
    ("Attack Rating against", "对"),
    ("Defense vs Missile", "对远程攻击的防御"),
    ("Defense vs Melee", "对近战攻击的防御"),
    ("Defense against Missiles", "对远程攻击的防御"),
    ("Defense vs", "对"),
    ("Chance to Block", "格挡几率"),
    ("Blocking", "格挡"),
    ("Missile Damage", "投射物伤害"),
    ("Cold Skill Damage", "冰冷技能伤害"),
    ("Fire Skill Damage", "火焰技能伤害"),
    ("Lightning Skill Damage", "闪电技能伤害"),
    ("Poison Skill Damage", "毒素技能伤害"),
    ("Skill Damage", "技能伤害"),
    ("Cold Damage", "冰冷伤害"),
    ("Fire Damage", "火焰伤害"),
    ("Lightning Damage", "闪电伤害"),
    ("Poison Damage", "毒素伤害"),
    ("Adds", "增加"),
    ("Enhanced Defense", "增强防御"),
    ("Increased Defense", "增加防御"),
    ("Defense", "防御"),
    ("Stamina Drain Reduced", "耐力消耗减少"),
    ("Stamina Drain", "耐力消耗"),
    ("Fire Absorb", "火焰吸收"),
    ("Cold Absorb", "冰冷吸收"),
    ("Lightning Absorb", "闪电吸收"),
    ("Magic Absorb", "魔法吸收"),
    ("Absorb", "吸收"),
    ("Movement Speed", "移动速度"),
    ("Increased Movement Speed", "增加移动速度"),
    ("Frozen", "冰冻"),
    ("While Frozen", "冰冻时"),
    ("While in Cold Status", "处于冰冻状态时"),
    ("in Cold Status", "处于冰冻状态"),
    ("Cold Enemies", "冰冷状态敌人"),
    ("Cold enemies", "冰冷状态敌人"),
    ("Reanimate as", "以…形态复活"),
    ("Reanimated as", "以…形态复活"),
    ("Reanimate", "复活"),
    ("Monster Density", "怪物密度"),
    ("Monsters have", "怪物拥有"),
    ("Players have", "玩家拥有"),
    ("Slain Monsters", "被击杀的怪物"),
    ("Slain", "被击杀"),
    ("Monsters", "怪物"),
    ("Monster", "怪物"),
    ("Enemies", "敌人"),
    ("Enemy", "敌人"),
    ("Undead", "不死生物"),
    ("Demons", "恶魔"),
    ("Demon", "恶魔"),
    ("Uber Boss", "超级首领"),
    ("Uber Bosses", "超级首领"),
    ("Bosses", "首领"),
    ("Boss", "首领"),
    ("Elites", "精英"),
    ("Elite", "精英"),
    ("Champions", "冠军"),
    ("Champion", "冠军"),
    ("Unique Monsters", "暗金怪物"),
    ("Magic Monsters", "魔法怪物"),
    ("on Level-Up", "升级时"),
    ("on Kill", "击杀时"),
    ("on Striking", "击中时"),
    ("on Attack", "攻击时"),
    ("on Casting", "施法时"),
    ("when Struck", "被击中时"),
    ("when Hit", "受击时"),
    ("when Equipped", "装备时"),
    ("after each Kill", "每次击杀后"),
    ("after each Demon Kill", "每次击杀恶魔后"),
    ("each Kill", "每次击杀"),
    ("Level-Up", "升级"),
    ("Level Up", "升级"),
    ("Chance to Cast", "几率施展"),
    ("Aura When Equipped", "装备时赋予灵气"),
    ("Auras", "灵气"),
    ("Aura", "灵气"),
    ("Charges", "次充能"),
    ("Charged", "充能"),
    ("Cooldown", "冷却时间"),
    ("Stacks", "层"),
    ("Stack", "叠加"),
    ("Splash Damage", "溅射伤害"),
    ("Splash", "溅射"),
    ("Melee", "近战"),
    ("Rarity", "稀有度"),
    ("Duration", "持续时间"),
    ("over", "持续"),
    ("seconds", "秒"),
    ("second", "秒"),
    ("Every", "每"),
    ("Kills", "次击杀"),
    ("Kill", "击杀"),
    ("Heal", "治疗"),
    ("Runes", "符文"),
    ("Rune", "符文"),
    ("Sockets", "孔"),
    ("Socketed", "凹槽"),
    ("Random", "随机"),
    ("Bonus", "加成"),
    ("Bonus to", "加成"),
    ("Character Level", "角色等级"),
    ("Character", "角色"),
    ("Per Character Level", "每级"),
    ("Based on Character Level", "以角色等级决定"),
    ("Based on Level", "以等级决定"),
    ("Based on Energy", "以精力决定"),
    ("Based on Strength", "以力量决定"),
    ("Based on Dexterity", "以敏捷决定"),
    ("Based on Vitality", "以体力决定"),
    ("Based on Mana", "以法力决定"),
    ("Based on Maximum Mana", "以最大法力决定"),
    ("Based on Stamina", "以耐力决定"),
    ("Based on", "以"),
    ("Limited to", "限于"),
    ("on class that this skill belongs to", "该类技能"),
    ("Only", "专用"),
    ("Sorceress", "法师"),
    ("Barbarian", "野蛮人"),
    ("Necromancer", "死灵法师"),
    ("Paladin", "圣骑士"),
    ("Amazon", "亚马逊"),
    ("Druid", "德鲁伊"),
    ("Assassin", "刺客"),
    ("Strength", "力量"),
    ("Dexterity", "敏捷"),
    ("Vitality", "体力"),
    ("Energy", "精力"),
    ("Life", "生命"),
    ("Mana", "法力"),
    ("Stamina", "耐力"),
    ("Maximum Life", "最大生命"),
    ("Maximum Mana", "最大法力"),
    ("Increased Life", "增加生命"),
    ("Increased Mana", "增加法力"),
    ("Damage", "伤害"),
    ("Defense", "防御"),
    ("Resistance", "抗性"),
    ("Resist", "抗性"),
    ("Attack", "攻击"),
    ("Skills", "技能"),
    ("Skill", "技能"),
    ("Level", "等级"),
    ("Chance", "几率"),
    ("Cast", "施展"),
    ("Speed", "速度"),
    ("Recovery", "恢复"),
    ("Rate", "速度"),
    ("Rating", "准确率"),
    ("Striking", "命中"),
    ("Target", "目标"),
    ("Monster", "怪物"),
    ("Enemy", "敌人"),
    ("Increase", "增加"),
    ("Increased", "增加"),
    ("Reduction", "减少"),
    ("Reduced", "减少"),
    ("Reduces", "减少"),
    ("Reduce", "减少"),
    ("Taken", "受到的"),
    ("Take", "受到"),
    ("Takes", "受到"),
    ("Gained", "获得"),
    ("Gain", "获得"),
    ("Gain as", "转化为"),
    ("as", "作为"),
    ("to", ""),
    ("All", "所有"),
    ("Maximum", "最大"),
    ("Minimum", "最小"),
    ("Enhanced", "增强"),
    ("Indestructible", "无法破坏"),
    ("Ethereal", "无形"),
    ("Durability", "耐久度"),
    ("Repairs", "修复"),
    ("Repair", "修复"),
    ("in", "在"),
    ("by", "减少"),
    ("Of", "之"),
    ("of", "之"),
    ("The", ""),
    ("the", ""),
    ("and", "与"),
    ("with", "与"),
    ("for", "对于"),
    ("on", "时"),
    ("per", "每"),
    ("vs", "对"),
    ("AOE", "范围"),
    ("AoE", "范围"),
    ("HP", "生命"),
    ("Null", ""),
    ("null", ""),
    ("nadds", ""),
    ("Spartan's", "斯巴达"),
    ("Grim Ward", "冷酷守卫"),
    ("Battle Cry", "战斗狂嗥"),
    ("War Cry", "战争狂嗥"),
    ("Shout", "大叫"),
    ("Battle Orders", "战斗指挥"),
    ("Battle Command", "战斗号令"),
    ("Find Potion", "寻找药剂"),
    ("Find Item", "寻找物品"),
    ("Grim Ward", "冷酷守卫"),
    ("Leap Attack", "跳跃攻击"),
    ("Leap", "跳跃"),
    ("Double Swing", "双手挥击"),
    ("Double Throw", "双手投掷"),
    ("Frenzy", "狂乱"),
    ("Whirlwind", "旋风"),
    ("Concentrate", "专心"),
    ("Berserk", "狂战士"),
    ("Stun", "击晕"),
    ("Bash", "重击"),
    ("Polearm", "长柄武器"),
    ("Mastery", "精通"),
    ("Sword Mastery", "剑精通"),
    ("Axe Mastery", "斧精通"),
    ("Mace Mastery", "锤精通"),
    ("Spear Mastery", "矛精通"),
    ("Throwing Mastery", "投掷精通"),
    ("Increased Stamina", "增加耐力"),
    ("Increased Speed", "增加速度"),
    ("Iron Skin", "铁布衫"),
    ("Natural Resistance", "自然抗性"),
    ("Cold Mastery", "冰冷支配"),
    ("Fire Mastery", "火焰支配"),
    ("Lightning Mastery", "闪电支配"),
    ("Warmth", "温暖"),
    ("Static Field", "静电力场"),
    ("Telekinesis", "心灵传动"),
    ("Teleport", "传送"),
    ("Hydra", "九头蛇"),
    ("Meteor", "陨石"),
    ("Blizzard", "暴风雪"),
    ("Frozen Orb", "冰封球"),
    ("Nova", "新星"),
    ("Chain Lightning", "连锁闪电"),
    ("Charged Bolt", "充能弹"),
    ("Fireball", "火球"),
    ("Fire Bolt", "火弹"),
    ("Fire Wall", "火墙"),
    ("Firestorm", "火风暴"),
    ("Molten Boulder", "熔岩巨岩"),
    ("Fissure", "裂隙"),
    ("Tornado", "龙卷风"),
    ("Twister", "小旋风"),
    ("Cyclone Armor", "飓风装甲"),
    ("Hurricane", "暴风"),
    ("Armageddon", "末日战场"),
    ("Volcano", "火山"),
    ("Arctic Blast", "极地风暴"),
    ("Ravens", "乌鸦"),
    ("Raven", "乌鸦"),
    ("Spirit Wolf", "幽灵狼"),
    ("Dire Wolf", "恐狼"),
    ("Grizzly", "灰熊"),
    ("Oak Sage", "橡木智者"),
    ("Heart of Wolverine", "狼獾之心"),
    ("Spirit of Barbs", "棘灵"),
    ("Werewolf", "狼人变化"),
    ("Werebear", "熊人变化"),
    ("Lycanthropy", "变形术"),
    ("Feral Rage", "野性狂暴"),
    ("Maul", "撞槌"),
    ("Fury", "狂怒"),
    ("Hunger", "饥饿"),
    ("Rabies", "狂犬病"),
    ("Fire Claws", "焰爪"),
    ("Claw Mastery", "爪精通"),
    ("Summon Spirit Wolf", "召唤幽灵狼"),
    ("Summon Dire Wolf", "召唤恐狼"),
    ("Summon Grizzly", "召唤灰熊"),
    ("Soulrend", "灵魂撕裂"),
    ("Fist of the Heavens", "天堂之拳"),
    ("Holy Bolt", "圣光弹"),
    ("Blessed Hammer", "祝福之锤"),
    ("Charge", "冲锋"),
    ("Smite", "重击"),
    ("Zeal", "热诚"),
    ("Sacrifice", "牺牲"),
    ("Holy Fire", "圣火"),
    ("Holy Freeze", "圣冰"),
    ("Holy Shock", "圣电"),
    ("Sanctuary", "圣堂"),
    ("Meditation", "冥想"),
    ("Conviction", "信念"),
    ("Fanaticism", "狂热"),
    ("Salvation", "救助"),
    ("Prayer", "祈祷"),
    ("Cleansing", "净化"),
    ("Redemption", "救赎"),
    ("Defiance", "反抗"),
    ("Blessed Aim", "祝福瞄准"),
    ("Might", "力量"),
    ("Vigor", "活力"),
    ("Concentration", "专注"),
    ("Thorns", "荆棘"),
    ("Bone Armor", "骨甲"),
    ("Bone Spirit", "骨灵"),
    ("Bone Spear", "骨矛"),
    ("Bone Wall", "骨墙"),
    ("Bone Prison", "骨牢"),
    ("Corpse Explosion", "尸爆"),
    ("Teeth", "牙"),
    ("Amplify Damage", "伤害加深"),
    ("Decrepify", "衰老"),
    ("Weaken", "削弱"),
    ("Terror", "恐惧"),
    ("Confuse", "迷乱"),
    ("Attract", "吸引"),
    ("Life Tap", "偷取生命"),
    ("Iron Maiden", "钢铁处女"),
    ("Poison Nova", "剧毒新星"),
    ("Poison Dagger", "毒素匕首"),
    ("Poison Explosion", "毒爆"),
    ("Summon Skeleton", "召唤骷髅"),
    ("Skeletal Mage", "骷髅法师"),
    ("Skeletal Mages", "骷髅法师"),
    ("Skeleton Mastery", "骷髅掌握"),
    ("Raise Skeleton", "复活骷髅"),
    ("Raise Skeletal Mage", "召唤骷髅法师"),
    ("Golem Mastery", "石魔掌握"),
    ("Clay Golem", "土魔"),
    ("Blood Golem", "血魔"),
    ("Iron Golem", "铁魔"),
    ("Fire Golem", "火魔"),
    ("Revive", "复活"),
    ("Desecrate", "亵渎"),
    ("Dark Pact", "黑暗契约"),
    ("Skeletons", "骷髅"),
    ("Skeleton", "骷髅"),
    ("Golems", "石魔"),
    ("Golem", "石魔"),
    ("Mages", "法师"),
    ("Mage", "法师"),
    ("Wolves", "狼"),
    ("Wolf", "狼"),
    ("Cloak of Shadows", "暗影斗篷"),
    ("Fade", "能量消解"),
    ("Venom", "毒牙"),
    ("Shadow Warrior", "影子战士"),
    ("Shadow Master", "影子大师"),
    ("Burst of Speed", "速度爆发"),
    ("Tiger Strike", "虎击"),
    ("Cobra Strike", "眼镜蛇击"),
    ("Phoenix Strike", "凤凰击"),
    ("Dragon Talon", "龙爪"),
    ("Dragon Claw", "双龙爪"),
    ("Dragon Tail", "神龙摆尾"),
    ("Dragon Flight", "飞龙在天"),
    ("Blades of Ice", "寒冰刃"),
    ("Claws of Thunder", "雷电爪"),
    ("Fists of Fire", "火焰拳"),
    ("Lightning Sentry", "雷光守卫"),
    ("Death Sentry", "亡者守卫"),
    ("Blade Sentinel", "刀刃之盾"),
    ("Blade Fury", "刃之怒"),
    ("Blade Shield", "刀刃护盾"),
    ("Fire Blast", "火焰爆震"),
    ("Shock Web", "雷电网"),
    ("Charged Bolt Sentry", "电能守卫"),
    ("Wake of Fire", "火焰震爆"),
    ("Wake of Inferno", "地狱火守卫"),
    ("Mind Blast", "心灵爆震"),
    ("Psychic Hammer", "心灵之锤"),
    ("Inner Sight", "内视"),
    ("Slow Missiles", "慢速箭"),
    ("Decoy", "诱饵"),
    ("Valkyrie", "女武神"),
    ("Jab", "戳刺"),
    ("Power Strike", "威力一击"),
    ("Poison Javelin", "毒枪"),
    ("Lightning Bolt", "闪电球"),
    ("Charged Strike", "充能一击"),
    ("Lightning Strike", "闪电攻击"),
    ("Impale", "刺穿"),
    ("Fend", "躲避"),
    ("Plague Javelin", "瘟疫标枪"),
    ("Freezing Arrow", "冻结之箭"),
    ("Exploding Arrow", "爆炸箭"),
    ("Immolation Arrow", "牺牲之箭"),
    ("Ice Arrow", "冰箭"),
    ("Cold Arrow", "冰箭"),
    ("Magic Arrow", "魔法箭"),
    ("Fire Arrow", "火箭"),
    ("Multiple Shot", "多重箭"),
    ("Guided Arrow", "导引箭"),
    ("Strafe", "炮轰"),
    ("Barrage", "弹幕"),
    ("Multishot", "多重射击"),
    ("Critical Strike", "致命一击"),
    ("Dodge", "闪避"),
    ("Avoid", "躲避"),
    ("Evade", "回避"),
    ("Penetrate", "穿刺"),
    ("Pierce", "穿刺"),
    ("Maiden", "少女"),
    ("Fusillade", "齐射"),
    ("Arrow", "箭"),
    ("Bow", "弓"),
    ("Crossbow", "十字弓"),
    ("Javelin", "标枪"),
    ("Spear", "矛"),
    ("Throw", "投掷"),
    ("Throwing", "投掷"),
    ("One-Hand", "单手"),
    ("Two-Hand", "双手"),
    ("Blast", "爆震"),
    ("Explosion", "爆炸"),
    ("Explode", "爆炸"),
    ("Fire", "火焰"),
    ("Cold", "冰冷"),
    ("Lightning", "闪电"),
    ("Poison", "毒素"),
    ("Ice", "冰"),
    ("Frost", "霜"),
    ("Bone", "白骨"),
    ("Blood", "鲜血"),
    ("Curse", "诅咒"),
    ("Curses", "诅咒"),
    ("Shadows", "影子"),
    ("Shadow", "影子"),
    ("Spirit", "精神"),
    ("Spirits", "精神"),
    ("Spells", "法术"),
    ("Spell", "法术"),
    ("Magic", "魔法"),
    ("Elemental", "元素"),
    ("Physical", "物理"),
    ("Armor", "护甲"),
    ("Helm", "头盔"),
    ("Shield", "盾牌"),
    ("Gloves", "手套"),
    ("Boots", "靴子"),
    ("Belt", "腰带"),
    ("Ring", "戒指"),
    ("Amulet", "项链"),
    ("Charm", "护身符"),
    ("Jewel", "珠宝"),
    ("Quiver", "箭袋"),
    ("Orb", "宝珠"),
    ("Orbs", "宝珠"),
    ("Weapon", "武器"),
    ("Weapons", "武器"),
    ("Item", "物品"),
    ("Items", "物品"),
    ("Frost Nova", "霜之新星"),
    ("Cannot be Repaired", "无法修复"),
    ("Cannot Be Repaired", "无法修复"),
    ("Repaired", "修复"),
    ("Repair 1 Durability", "修复 1 点耐久度"),
    ("Cold Resist", "冰冷抗性"),
    ("Fire Resist", "火焰抗性"),
    ("Lightning Resist", "闪电抗性"),
    ("Poison Resist", "毒素抗性"),
    ("Maximum Shadows", "最大影子数量"),
    ("Maximum Spirits", "最大灵体数量"),
    ("Repairs 1 Durability in", "修复耐久度，每"),
    ("Kill Counter", "击杀计数"),
    ("Increased Maximum", "增加最大"),
    ("Decreased", "减少"),
    ("On Kill", "击杀时"),
    ("On Striking", "击中时"),
    ("When Equipped", "装备时"),
    ("When Hit", "受击时"),
    ("When Struck", "被击中时"),
    ("on Equip", "装备时"),
    ("While Equipped", "装备时"),
    ("Radius", "范围"),
    ("Strength Based", "以力量决定"),
    ("Sacred Orb", "圣化宝珠"),
    ("World Stone Shard", "世界之石碎片"),
    ("Demonic Cube", "恶魔魔方"),
    ("Infernal Kiln", "炼狱熔炉"),
    ("Corrupted", "腐化"),
    ("Corrupt", "腐化"),
    ("Sacred", "神圣"),
    ("Sacreds", "圣物"),
    ("Mythic Orb", "神话宝珠"),
    ("Divine Orb", "神圣宝珠"),
    ("Map", "地图"),
    ("Maps", "地图"),
    ("Dungeons", "地下城"),
    ("Dungeon", "地下城"),
    ("Headhunter", "猎头者"),
    ("Kill Counter", "击杀计数"),
    ("League", "赛季"),
    ("Season", "赛季"),
    ("Fate Card", "命运卡牌"),
    ("Ascendancy", "飞升"),
    ("Essence", "精华"),
    ("Essences", "精华"),
    ("Terror of Opulence", "财富恐怖"),
    ("T4 Dungeons", "T4 地下城"),
    ("T3 Dungeons", "T3 地下城"),
    ("T2 Dungeons", "T2 地下城"),
    ("T1 Dungeons", "T1 地下城"),
    ("T5 Dungeons", "T5 地下城"),
    ("T4", "T4"),
    ("T3", "T3"),
    ("T2", "T2"),
    ("T1", "T1"),
    ("T5", "T5"),
]

# 词级兜底词典 (短语未命中时的单词翻译)
WORD_DICT = {
    "to": "", "the": "", "of": "之", "and": "与", "in": "在", "on": "时", "a": "", "an": "",
    "adds": "增加", "add": "增加", "gained": "获得", "gain": "获得", "per": "每", "based": "基于",
    "damage": "伤害", "level": "等级", "chance": "几率", "cast": "施展", "resist": "抗性",
    "have": "拥有", "enhanced": "增强", "fire": "火焰", "lightning": "闪电", "maximum": "最大",
    "monsters": "怪物", "monster": "怪物", "cold": "冰冷", "defense": "防御", "skill": "技能",
    "skills": "技能", "life": "生命", "attack": "攻击", "poison": "毒素", "mana": "法力",
    "magic": "魔法", "striking": "命中", "hit": "命中", "rating": "准确率", "when": "时",
    "character": "角色", "physical": "物理", "reduced": "减少", "reduction": "减少", "reduce": "减少",
    "by": "减少", "faster": "更快", "taken": "受到的", "take": "受到", "takes": "受到",
    "enemy": "敌人", "enemies": "敌人", "resistance": "抗性", "resistances": "抗性", "stolen": "偷取",
    "seconds": "秒", "second": "秒", "extra": "额外", "as": "作为", "find": "寻找",
    "casting": "施法", "over": "持续", "minimum": "最小", "wounds": "伤口", "open": "撕裂",
    "gold": "金币", "strength": "力量", "all": "所有", "dexterity": "敏捷", "rate": "速度",
    "absorb": "吸收", "this": "此", "speed": "速度", "class": "职业", "that": "该",
    "equipped": "装备", "limited": "限于", "belongs": "属于", "strike": "打击", "attacker": "攻击者",
    "kill": "击杀", "item": "物品", "items": "物品", "undead": "不死生物", "each": "每个",
    "aura": "灵气", "auras": "灵气", "after": "之后", "energy": "精力", "better": "更好的",
    "getting": "获得", "barbarian": "野蛮人", "deadly": "致命", "replenish": "回复", "amazon": "亚马逊",
    "demons": "恶魔", "demon": "恶魔", "sorceress": "法师", "charges": "次充能", "paladin": "圣骑士",
    "recovery": "恢复", "crushing": "压碎", "blow": "打击", "druid": "德鲁伊", "pierce": "穿刺",
    "curse": "诅咒", "curses": "诅咒", "vitality": "体力", "density": "密度", "against": "对",
    "levels": "等级", "increase": "增加", "increased": "增加", "you": "你", "your": "你的",
    "from": "从", "block": "格挡", "bolt": "弹", "bonus": "加成", "mastery": "精通",
    "assassin": "刺客", "experience": "经验值", "radius": "范围", "target": "目标", "duration": "持续时间",
    "amplify": "加深", "light": "光照", "stamina": "耐力", "regenerate": "回复", "gained": "获得",
    "skeleton": "骷髅", "skeletons": "骷髅", "drain": "消耗", "frost": "霜", "missile": "投射物",
    "missiles": "投射物", "run": "跑步", "walk": "行走", "chain": "连锁", "lower": "降低",
    "charged": "充能", "effect": "效果", "bone": "白骨", "holy": "神圣", "blocking": "格挡",
    "socketed": "凹槽", "summoning": "召唤", "requirements": "需求", "requirement": "需求",
    "is": "是", "summon": "召唤", "ball": "球", "meteor": "陨石", "ice": "冰", "tornado": "龙卷风",
    "frequency": "频率", "be": "", "frozen": "冰冻", "equal": "等于", "reanimate": "复活",
    "if": "如果", "than": "超过", "corrupted": "腐化", "spear": "矛", "rarity": "稀有度",
    "iron": "铁", "twister": "小旋风", "shadow": "影子", "firestorm": "火风暴", "raise": "复活",
    "can": "可以", "movement": "移动", "stack": "叠加", "stacks": "层", "static": "静态",
    "field": "力场", "shield": "盾牌", "blaze": "炽焰之径", "barrage": "弹幕", "greater": "更大",
    "battle": "战斗", "every": "每", "fist": "拳", "heavens": "天堂", "javelin": "标枪",
    "elemental": "元素", "while": "同时", "melee": "近战", "cooldown": "冷却", "maiden": "少女",
    "fusillade": "齐射", "cry": "狂嗥", "golem": "石魔", "cannot": "无法", "disciplines": "训练",
    "blizzard": "暴风雪", "ravens": "乌鸦", "cyclone": "飓风", "spirit": "精神", "offensive": "攻击",
    "soul": "灵魂", "die": "死亡", "blast": "爆震", "velocity": "速度", "shot": "射击",
    "shape": "变形", "shifting": "变形", "slows": "减慢", "leap": "跳跃", "warrior": "战士",
    "decrepify": "衰老", "slow": "减慢", "heal": "治疗", "splash": "溅射", "weaken": "削弱",
    "hydra": "九头蛇", "molten": "熔岩", "boulder": "巨岩", "vigor": "活力", "masteries": "精通",
    "freezes": "冰冻", "teleport": "传送", "arrow": "箭", "causes": "使", "flee": "逃跑",
    "blinds": "致盲", "base": "基底", "martial": "武术", "arts": "武术", "buff": "增益",
    "revive": "复活", "venom": "毒牙",    "repairs": "修复", "repair": "修复", "seconds": "秒", "radius": "范围",
 "repairs": "修复", "durability": "耐久度", "orb": "宝珠",
    "plus": "加", "has": "拥有", "defensive": "防御", "rage": "狂暴", "shadows": "影子",
    "wall": "墙", "sanctuary": "圣堂", "warmth": "温暖", "terror": "恐惧", "corpse": "尸体",
    "explosion": "爆炸", "enchant": "强化", "passive": "被动", "headhunter": "猎头者",
    "thorns": "荆棘", "critical": "致命", "heart": "之心", "wolverine": "狼獾", "modified": "已修改",
    "up": "升级", "modifiers": "属性", "modifier": "属性", "arcane": "奥术", "efficiency": "效率",
    "returned": "返还", "traps": "陷阱", "shattered": "破碎", "marrow": "骨髓", "reinforce": "强化",
    "warcries": "战嗥", "length": "持续时间", "soulrend": "灵魂撕裂", "maul": "撞槌",
    "cloak": "斗篷", "fissure": "裂隙", "spell": "法术", "multiplier": "倍率", "skeletal": "骷髅",
    "wolf": "狼", "taunt": "嘲讽", "archers": "弓箭手", "hp": "生命", "fury": "狂怒",
    "no": "无", "zeal": "热诚", "desecrate": "亵渎", "tap": "偷取", "combat": "战斗",
    "fade": "能量消解", "overload": "过载", "one": "一", "spartan": "斯巴达", "max": "最大",
    "might": "力量", "confuse": "迷乱", "random": "随机", "grim": "冷酷", "ward": "守卫",
    "attacks": "攻击", "deal": "造成", "blood": "鲜血", "valkyrie": "女武神", "bow": "弓",
    "crossbow": "十字弓", "teeth": "牙", "blessed": "祝福", "hammer": "锤", "dark": "黑暗",
    "pact": "契约",
}

# 物品类型显示名
ITEM_TYPE_DICT = {
    "Axe Class": "斧类", "Bow Class": "弓类", "Claw class": "爪类", "Crossbow Class": "十字弓类",
    "Dagger Class": "匕首类", "Head": "头颅", "Javelin Class": "标枪类", "Mace Class": "锤类",
    "Paladin Helmet": "圣骑士头盔", "Polearm Class": "长柄武器类", "Spear Class": "矛类",
    "Staff Class": "法杖类", "Sword Class": "剑类", "Two-Handed": "双手",
    "1 Handed Melee Weapon": "单手近战武器", "2 Handed Melee Weapon": "双手近战武器",
    "Missile Weapon": "远程武器", "Throwing Weapon": "投掷武器",
    "Any Shield": "任意盾牌", "Shield": "盾牌", "Armor": "护甲", "Helm": "头盔",
    "Gloves": "手套", "Boots": "靴子", "Belt": "腰带", "Circlet": "头环",
    "Druid Pelt": "德鲁伊毛皮", "Barbarian Helm": "野蛮人头盔", "Necromancer Head": "死灵法师头颅",
    "Paladin Shield": "圣骑士盾牌", "Amazon Bow": "亚马逊弓", "Sorceress Orb": "法师宝珠",
    "Weapon": "武器", "Jewel": "珠宝", "Amulet": "项链", "Ring": "戒指", "Charm": "护身符",
    "Quiver": "箭袋", "Grand Charm": "大型护身符", "Ornate Charm": "华丽护身符",
    "Small Charm": "小型护身符", "Large Charm": "中型护身符", "Any Armor": "任意护甲",
    "Map": "地图", "Bow/Crossbow Quiver": "弓/十字弓箭袋", "Class Specific": "职业限定",
}

# 阶位
TIER_DICT = {"Normal": "普通", "Exceptional": "扩展", "Elite": "精英", "Sacred": "神圣"}

# 职业名
CLASS_DICT = {
    "Amazon": "亚马逊", "Barbarian": "野蛮人", "Necromancer": "死灵法师", "Paladin": "圣骑士",
    "Sorceress": "法师", "Druid": "德鲁伊", "Assassin": "刺客",
}
